workshop_homepage:
    pattern:  /home/
    defaults: { _controller: AppBundle:Default:index }
home:
    pattern: /
    defaults: { _controller: FrameworkBundle:Redirect:redirect,route: workshop_homepage, permanent: true }
call:
    pattern: /CallForPapers
    defaults: { _controller: AppBundle:Default:call }
instrucciones:
    pattern: /InstructionsForAuthors
    defaults: { _controller: AppBundle:Default:instrucciones }
programa:
    pattern: /Program
    defaults: { _controller: AppBundle:Default:programa }
comite:
    pattern: /Committee
    defaults: { _controller: AppBundle:Default:comite }
venue:
    pattern: /Venue
    defaults: { _controller: AppBundle:Default:venue }
